cluster:
  name: kubelab

kubernetes:
  version: "1.34"

network:
  podSubnet: "10.244.0.0/16"

nodes:
  control:
    hostname: control
    ip: 192.168.178.51

  workers:
    - hostname: worker01
      ip: 192.168.178.52

    - hostname: worker02
      ip: 192.168.178.53

ssh:
  user: student
  password: student

components:
  calico: true
  localStorage: true
  metricsServer: true
  ingress: true

downloads:
  calico: "https://raw.githubusercontent.com/projectcalico/calico/v3.30.3/manifests/calico.yaml"
  storage: "https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml"
  ingress: "https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.12.1/deploy/static/provider/baremetal/deploy.yaml"
  metrics: "https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml"
